name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - run: sudo apt-get update && sudo apt-get install -y shellcheck
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint
  build:
    needs: 
      - lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: tar czf letusreshade-decky.tgz dist
      - uses: actions/upload-artifact@v4
        with:
          name: letusreshade-decky
          path: letusreshade-decky.tgz
  # Commented out until tests are implemented
  # test:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - build
  #   steps:
  #     - uses: actions/checkout@v5
  #     - uses: actions/download-artifact@v5
  #       with:
  #         name: letusreshade-decky
  #     - run: |
  #         tar xf letusreshade-decky.tgz
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: 24
  #         cache: pnpm
  #     - run: pnpm install --frozen-lockfile
  #     - run: pnpm test

